---
name: "Crunchyroll Metadata"
guid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version: "1.2.3.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Fetches anime metadata from Crunchyroll with intelligent season and episode mapping."
description: >
  A Jellyfin plugin that provides anime metadata from Crunchyroll. 
  Features intelligent season mapping to handle cases where different databases 
  treat seasons as separate works, and automatic episode offset calculation 
  to correctly match local episode numbering with Crunchyroll's continuous numbering scheme.
category: "Metadata"
owner: "ocnaibill"
artifacts:
- "Jellyfin.Plugin.Crunchyroll.dll"
changelog: >
  1.2.3.0 - API Stealth Improvements
    - Updated API client to mimic Android TV behavior (User-Agent, Headers)
    - Updated authentication tokens to less restricted client ID
    - Added ETP-Anonymous-ID header to improve request legitimacy
    - Maintains FlareSolverr fallback if direct API access still fails

  1.2.2.0 - Scraping fallback improvements
    - Implement caching strategy for scraping seasons and episodes
    - Fix API calls being attempted when scraping mode is active
    - Fallback to scraping for GetSeasons and GetEpisodes calls

  1.2.1.0 - Hotfix for FlareSolverr detection
    - Relaxed Cloudflare detection logic to work with all 403 responses
    - Added better warnings when FlareSolverr URL is missing
    - Fixed fallback not triggering on some Cloudflare challenges

  1.2.0.0 - FlareSolverr support
    - Add FlareSolverr integration for Cloudflare bypass
    - Automatic detection of Cloudflare blocks
    - HTML scraping fallback when API is blocked
    - New configuration option for FlareSolverr URL
    - Improved error handling and logging

  1.1.0.0 - Authentication support
    - Add anonymous authentication for Crunchyroll API
    - Implement Bearer token for all API requests
    - Add token caching with automatic renewal
    - Fix API access issues with proper authentication

  1.0.0.0 - Initial release
    - Series metadata provider
    - Season metadata provider with intelligent mapping
    - Episode metadata provider with offset calculation
    - Image providers for series and episodes
    - Multi-language support (pt-BR, en-US, ja-JP, and more)
