---
name: "Crunchyroll Metadata"
guid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version: "1.4.1.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Fetches anime metadata from Crunchyroll with intelligent season and episode mapping."
description: >
  A Jellyfin plugin that provides anime metadata from Crunchyroll. 
  Features intelligent season mapping to handle cases where different databases 
  treat seasons as separate works, and automatic episode offset calculation 
  to correctly match local episode numbering with Crunchyroll's continuous numbering scheme.
category: "Metadata"
owner: "ocnaibill"
artifacts:
- "Jellyfin.Plugin.Crunchyroll.dll"
changelog: >
  1.4.1.0 - Token Fix
    - Reverted to crunchyroll-rs token (Python package token was inactive)
    - Verified working via curl_cffi testing

  1.4.0.0 - Authentication Overhaul
    - Simplified User-Agent to reduce fingerprint surface
    - Implemented Refresh Token support for seamless session renewal
    - Automatic fallback to full login when refresh token expires

  1.3.7.0 - Thumbnails & Stealth
    - Upgraded fallback scraper thumbnails to 1080p resolution
    - Added random jitter delay to API requests to reduce block frequency
    - Improved stealth against rate limiting

  1.3.6.0 - Concurrency Fixes
    - Fixed race condition where multiple threads would attempt authentication simultaneously
    - Handled 429 Too Many Requests (Error 1015) as a Cloudflare block trigger
    - Prevents authentication spam when scraping mode is activated

  1.3.5.0 - Robustness Improvements
    - Added automatic retry on 401 Unauthorized (expired tokens)
    - Improved detection of Cloudflare blocks (403) on API calls
    - Automatically switches to scraping mode globally when blocked

  1.3.4.0 - Critical Rate Limit Fix
    - Made authentication state static to persist across requests
    - Prevents 429 Too Many Requests bans by sharing tokens between providers
    - Added backoff protection (10s cooldown) for failed auth attempts

  1.3.3.0 - Login Fixes
    - Added missing device_id and device_type to authentication requests
    - Improved error messages for invalid credentials
    - Consistent device identifiers between headers and body

  1.3.2.0 - Hotfix 2
    - Force update to ensure User-Agent fix is applied

  1.3.1.0 - Hotfix
    - Fixed System.FormatException when setting User-Agent header (Thank you .NET HttpClient)

  1.3.0.0 - User Login Support
    - Added ability to login with Crunchyroll credentials (Email/Password)
    - Authenticated requests are less likely to be blocked by Cloudflare
    - Configurable via plugin settings page
  
  1.2.3.0 - API Stealth Improvements
    - Updated API client to mimic Android TV behavior (User-Agent, Headers)
    - Updated authentication tokens to less restricted client ID
    - Added ETP-Anonymous-ID header to improve request legitimacy
    - Maintains FlareSolverr fallback if direct API access still fails

  1.2.2.0 - Scraping fallback improvements
    - Implement caching strategy for scraping seasons and episodes
    - Fix API calls being attempted when scraping mode is active
    - Fallback to scraping for GetSeasons and GetEpisodes calls

  1.2.1.0 - Hotfix for FlareSolverr detection
    - Relaxed Cloudflare detection logic to work with all 403 responses
    - Added better warnings when FlareSolverr URL is missing
    - Fixed fallback not triggering on some Cloudflare challenges

  1.2.0.0 - FlareSolverr support
    - Add FlareSolverr integration for Cloudflare bypass
    - Automatic detection of Cloudflare blocks
    - HTML scraping fallback when API is blocked
    - New configuration option for FlareSolverr URL
    - Improved error handling and logging

  1.1.0.0 - Authentication support
    - Add anonymous authentication for Crunchyroll API
    - Implement Bearer token for all API requests
    - Add token caching with automatic renewal
    - Fix API access issues with proper authentication

  1.0.0.0 - Initial release
    - Series metadata provider
    - Season metadata provider with intelligent mapping
    - Episode metadata provider with offset calculation
    - Image providers for series and episodes
    - Multi-language support (pt-BR, en-US, ja-JP, and more)
